const fs = require('fs');

let content = fs.readFileSync('src/App.tsx', 'utf-8');

const replacements = {
  'マイスタジオ': 'My Studio',
  'ぷちデレラ': 'Petit CG',
  'ガチャ': 'Gacha',
  'レッスン': 'Lesson',
  'フリートレード': 'Free Trade',
  '閉じる': 'Close',
  'プロダクションマッチ': 'Production Match',
  'フェスティバル': 'Festival',
  'レッスン&特訓': 'Lesson & Training',
  'お仕事': 'Work',
  'LIVEバトル': 'LIVE Battle',
  '編成': 'Formation',
  'アイテム': 'Items',
  'ショップ': 'Shop',
  'アイテム一覧': 'Item List',
  '贈り物': 'Gifts',
  '交換': 'Exchange',
  'アイドル一覧移籍': 'Idol List/Transfer',
  '女子寮トレーナールーム': 'Dorm/Trainer Room',
  'プロダクション': 'Production',
  'プロフィール': 'Profile',
  'その他': 'Others',
  'お気に入り': 'Favorites',
  '資料室': 'Archive',
  'ゲームセンター': 'Game Center',
  'サウンドブース': 'Sound Booth',
  '設定': 'Settings',
  'ヘルプ': 'Help',
  'トップ': 'Top',
  '戻る': 'Back',
  '進む': 'Forward',
  '再読み込み': 'Reload',
  'メニュー': 'Menu',
  'どんなポーズでも、オールOKだよっ！': 'Any pose is totally OK!',
  '守備編成': 'Def Formation',
  'ぷち鳥': 'Petit Bird',
  'レッスン & 特訓': 'Lesson & Training',
  'スタミナ': 'Stamina',
  '攻コスト': 'Atk Cost',
  'アイドルプロデュース': 'Idol Produce',
  'ラウンド終了まで': 'Until Round Ends',
  '残り': 'Remaining ',
  'ぷちTOP': 'Petit TOP',
  'ぷちレッスン': 'Petit Lesson',
  'ボード': 'Board',
  'ぷちプロフ': 'Petit Profile',
  'ぷちメニュー': 'Petit Menu',
  '誘惑イビル': 'Temptation Evil',
  '所持ぷちマニー': 'Petit Money',
  '所持テクニカルpt': 'Technical pt',
  'ソロ': 'Solo',
  'ユニット': 'Unit',
  '海の向こうで飛び級やってたけど、だいたいのコト覚えたらつまんなく思えちゃってー♪': 'I skipped grades overseas, but once I learned most things, it got boring~♪',
  '訪問': 'Visit',
  'モーション': 'Motion',
  'テクニカルボード': 'Technical Board',
  'ぷちショップ': 'Petit Shop',
  'ぷち編成': 'Petit Formation',
  '衣装設定': 'Outfit Settings',
  '※推奨環境は以下になります。': '* Recommended environment is as follows.',
  'iPhone 5 以降 かつ iOS 8.0 以上の端末': 'iPhone 5 or later and iOS 8.0+',
  'Android 4.2 以上搭載の端末': 'Android 4.2+ devices',
  '※タブレットを含む一部非対応の端末もございます。': '* Some devices including tablets are not supported.',
  '※推奨環境であっても一部端末で動作しない場合がございます。': '* May not work on some devices even in recommended environment.',
  '※いいね！された回数は、毎週月曜0時にリセットされます。': "* 'Likes' are reset every Monday at 0:00.",
  'マイスタジオへ': 'To My Studio',
  'ページTOPへ戻る': 'Back to TOP',
  'ユニット編成': 'Unit Formation',
  '総攻': 'Total Atk',
  '総守': 'Total Def',
  '総コスト': 'Total Cost',
  'コスト': 'Cost',
  '攻': 'Atk',
  '守': 'Def',
  'はずす': 'Remove',
  '変更': 'Change',
  'アイドル': 'Idols',
  "replace('一覧', '一覧\\\\n').replace('女子寮', '女子寮\\\\n')": "replace('List', 'List\\\\n').replace('Dorm', 'Dorm\\\\n')",
  'PRA': 'PRA'
};

for (const [jp, en] of Object.entries(replacements)) {
  content = content.split(jp).join(en);
}

fs.writeFileSync('src/App.tsx', content);
